name: Build and Publish docker

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build_and_publish_images:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      IMAGE: ghcr.io/lucky3028/del-ghcr
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: lucky3028
          password: ${{ secrets.GHCR_PAT }}

      - name: Prepare dummy
        run: |
          curl -s https://api.github.com/repos/Lucky3028/create-dummy-toml/releases/latest \
            | grep "browser_download_url" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -
          chmod +x create-dummy-toml
          ./create-dummy-toml
      - name: Build builder image
        run: docker build --target builder --cache-from $IMAGE:builder -t $IMAGE:builder --build-arg BUILDKIT_INLINE_CACHE=1 .
      - name: Build image
        run: docker build --cache-from $IMAGE:builder --cache-from $IMAGE:latest -t $IMAGE:latest --build-arg BUILDKIT_INLINE_CACHE=1 .

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push $IMAGE:builder &
          docker push $IMAGE:latest &
          wait

      - name: Remove untagged image
        if: github.ref == 'refs/heads/main'
        run: docker run $IMAGE:latest -t ${{ secrets.GHCR_PAT }} -c $(echo $IMAGE | cut -d \/ -f 3)
