name: Scan dockerfile by Trivy

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 1' # 毎週月曜日の9時(JST)

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/lucky3028/del-ghcr:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - uses: actions/github-script@v3
        if: failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { GITHUB_SERVER_URL, GITHUB_REPOSITORY, GITHUB_RUN_ID } = process.env
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Dockerイメージに脆弱性が発見されました',
              body: `詳細: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}`,
            })